### ISSUE TITLE
Wrong type when attribute name and type name clash

### ISSUE THREAD

**Issue by arnimarj** [python-attrs/attrs#1041]
I stumbled upon an interesting issue: when an attribute name and type name clash inside a class definition the attribute type is wrong:

```python
import attr

@attr.s
class AT_Base:
	a: str = attr.ib()


@attr.s
class AT_Owner:
	# attribute name and type name clash
	AT_Base: AT_Base = attr.ib()


for f in attr.fields(AT_Owner):
	print('AT', f.name, f.type)
```

This will output:

```shell
AT AT_Base _CountingAttr(counter=23, _default=NOTHING, repr=True, eq=True, order=True, hash=None, init=True, on_setattr=None, metadata={})
```

I tested the same thing using `dataclasses` and there the type seems to resolve correctly:

```python
import dataclasses


@dataclasses.dataclass
class DC_Base:
	a: str


@dataclasses.dataclass
class DC_Owner:
	DC_Base: DC_Base


for f in dataclasses.fields(DC_Owner):
	print('DC', f.name, f.type)
```

which outputs:

```shell
DC DC_Base <class '__main__.DC_Base'>
```

These were tested on `attrs==22.1.0` and Python `3.10.8`

**Comment by arnimarj** [comment]
Interestingly...this seems to work:

```python
import attrs

@attrs.define
class AT_Base:
	a: str


@attrs.define
class AT_Owner:
	AT_Base: AT_Base
```

as does:

```python
import attr

@attr.s(auto_attribs=True)
class AT_Base:
	a: str


@attr.s(auto_attribs=True)
class AT_Owner:
	AT_Base: AT_Base
```

But this does not:

```python
import attrs

@attrs.define(auto_attribs=False)
class AT_Base:
	a: str = attrs.field()


@attrs.define(auto_attribs=False)
class AT_Owner:
	AT_Base: AT_Base = attrs.field()


for f in attrs.fields(AT_Owner):
	print('AT', f.name, f.type)
```

**Comment by hynek** [comment]
`auto_attribs=False` (which is default in the old `attr.s`) APIs should ignore type annotations so I guess it gets confused by symbols of two types floating around? It's definitely not a bug, I would call it undefined behavior. :)

**Comment by arnimarj** [comment]
Indeed, updating the dataclasses examples to use `dataclasses.field()` does this:

``shell
Traceback (most recent call last):
  File "/home/arni/dohop/libdohop/dc.py", line 12, in <module>
    class DC_Owner:
  File "/home/arni/.pyenv/versions/3.10.8/lib/python3.10/dataclasses.py", line 1185, in dataclass
    return wrap(cls)
  File "/home/arni/.pyenv/versions/3.10.8/lib/python3.10/dataclasses.py", line 1176, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
  File "/home/arni/.pyenv/versions/3.10.8/lib/python3.10/dataclasses.py", line 1094, in _process_class
    str(inspect.signature(cls)).replace(' -> None', ''))
  File "/home/arni/.pyenv/versions/3.10.8/lib/python3.10/inspect.py", line 3207, in __str__
    formatted = str(param)
  File "/home/arni/.pyenv/versions/3.10.8/lib/python3.10/inspect.py", line 2724, in __str__
    formatannotation(self._annotation))
  File "/home/arni/.pyenv/versions/3.10.8/lib/python3.10/inspect.py", line 1369, in formatannotation
    return repr(annotation)
  File "/home/arni/.pyenv/versions/3.10.8/lib/python3.10/dataclasses.py", line 283, in __repr__
    return ('Field('
  File "/home/arni/.pyenv/versions/3.10.8/lib/python3.10/dataclasses.py", line 283, in __repr__
    return ('Field('
  File "/home/arni/.pyenv/versions/3.10.8/lib/python3.10/dataclasses.py", line 283, in __repr__
    return ('Field('
  [Previous line repeated 491 more times]
```
