### ISSUE TITLE
pyproject.licence is valid by multiple definitions

### ISSUE THREAD

**Issue by Tlunch** [python-attrs/attrs#1376]
When using the setup.py to compile 24.2.0

```log
configuration error: `project.license` must be valid exactly by one definition (2 matches found):

    - keys:
        'file': {type: string}
      required: ['file']
    - keys:
        'text': {type: string}
      required: ['text']
```

This is compiling from a source tar ball download from pypi.
This is using pip 24.3.1
This is using setuptools 75.3.0
This is using python 3.8.17

The full log is 
```log
/home/openwrt/gateworks-openwrt/staging_dir/hostpkg/bin/python3.8  setup.py   install --prefix="/usr" --root="/home/openwrt/gateworks-openwrt/build_dir/target-aarch64_generic_musl/pypi/attrs-24.2.0/ipkg-install" --single-version-externally-managed
configuration error: `project.license` must be valid exactly by one definition (2 matches found):

    - keys:
        'file': {type: string}
      required: ['file']
    - keys:
        'text': {type: string}
      required: ['text']

DESCRIPTION:
    `Project license <https://peps.python.org/pep-0621/#license>`_.

GIVEN VALUE:
    "MIT"

OFFENDING RULE: 'oneOf'

DEFINITION:
    {
        "oneOf": [
            {
                "properties": {
                    "file": {
                        "type": "string",
                        "$$description": [
                            "Relative path to the file (UTF-8) which contains the license for the",
                            "project."
                        ]
                    }
                },
                "required": [
                    "file"
                ]
            },
            {
                "properties": {
                    "text": {
                        "type": "string",
                        "$$description": [
                            "The license of the project whose meaning is that of the",
                            "`License field from the core metadata",
                            "<https://packaging.python.org/specifications/core-metadata/#license>`_."
                        ]
                    }
                },
                "required": [
                    "text"
                ]
            }
        ]
    }
[91mTraceback (most recent call last):
  File "setup.py", line 6, in <module>
    setuptools.setup(version=os.environ['PY_PKG_VERSION'])
  File "/home/openwrt/gateworks-openwrt/staging_dir/hostpkg/lib/python3.8/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
  File "/home/openwrt/gateworks-openwrt/staging_dir/hostpkg/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 157, in setup
    dist.parse_config_files()
  File "/home/openwrt/gateworks-openwrt/staging_dir/hostpkg/lib/python3.8/site-packages/setuptools/dist.py", line 655, in parse_config_files
    pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
  File "/home/openwrt/gateworks-openwrt/staging_dir/hostpkg/lib/python3.8/site-packages/setuptools/config/pyprojecttoml.py", line 71, in apply_configuration
    config = read_configuration(filepath, True, ignore_option_errors, dist)
  File "/home/openwrt/gateworks-openwrt/staging_dir/hostpkg/lib/python3.8/site-packages/setuptools/config/pyprojecttoml.py", line 139, in read_configuration
    validate(subset, filepath)
  File "/home/openwrt/gateworks-openwrt/staging_dir/hostpkg/lib/python3.8/site-packages/setuptools/config/pyprojecttoml.py", line 60, in validate
    raise ValueError(f"{error}\n{summary}") from None
ValueError: invalid pyproject.toml config: `project.license`.
configuration error: `project.license` must be valid exactly by one definition (2 matches found):

    - keys:
        'file': {type: string}
      required: ['file']
    - keys:
        'text': {type: string}
      required: ['text']
```

**Comment by Tlunch** [comment]
The guide to writing `pyproject.toml` files suggests that as you have a licence file in the project you should use the `license = {file = "LICENSE"}` file definition instead of text.
