### ISSUE TITLE
Docs don’t build with Sphinx 1.6

### ISSUE THREAD

**Issue by hynek** [python-attrs/attrs#190]
I have no idea what’s going on, but the deprecation warnings should be fixed too.

<details>
```
Running Sphinx v1.6.1
loading pickled environment... not yet created
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 11 source files that are out of date
updating environment: 11 added, 0 changed, 0 removed
reading sources... [  9%] api
/Users/hynek/Projects/attrs/.tox/docs/lib/python3.6/site-packages/sphinx/environment/__init__.py:680: RemovedInSphinx17Warning: html_use_smartypants option is deprecated. Use the smart_quotes option in docutils.conf instead.
  RemovedInSphinx17Warning)
reading sources... [ 18%] backward-compatibility
/Users/hynek/Projects/attrs/.tox/docs/lib/python3.6/site-packages/sphinx/environment/__init__.py:680: RemovedInSphinx17Warning: html_use_smartypants option is deprecated. Use the smart_quotes option in docutils.conf instead.
  RemovedInSphinx17Warning)
reading sources... [ 27%] changelog
reading sources... [ 36%] contributing
reading sources... [ 45%] examples
reading sources... [ 54%] extending
reading sources... [ 63%] how-does-it-work
reading sources... [ 72%] index
reading sources... [ 81%] license
reading sources... [ 90%] overview
reading sources... [100%] why

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  9%] api
writing output... [ 18%] backward-compatibility
writing output... [ 27%] changelog
writing output... [ 36%] contributing
writing output... [ 45%] examples
writing output... [ 54%] extending
writing output... [ 63%] how-does-it-work
writing output... [ 72%] index
writing output... [ 81%] license
writing output... [ 90%] overview
writing output... [100%] why

generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.
docs runtests: commands[1] | sphinx-build -W -b doctest -d /Users/hynek/Projects/attrs/.tox/docs/tmp/doctrees docs docs/_build/html
Running Sphinx v1.6.1
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [doctest]: targets for 11 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
running tests...

Document: examples
------------------
1 items passed all tests:
 123 tests in default
123 tests in 1 items.
123 passed and 0 failed.
Test passed.

Document: api
-------------

Warning, treated as error:
**********************************************************************
File "api.rst", line 199, in default
Failed example:
    @attr.s
Exception raised:
    Traceback (most recent call last):
      File "/Users/hynek/.pyenv/versions/3.6.1/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "/Users/hynek/Projects/attrs/.tox/docs/lib/python3.6/site-packages/sphinx/ext/doctest.py", line 448, in compile
        return compile(code, name, self.type, flags, dont_inherit)
      File "<doctest default[0]>", line 1
        @attr.s
              ^
    SyntaxError: unexpected EOF while parsing

ERROR: InvocationError: '/Users/hynek/Projects/attrs/.tox/docs/bin/sphinx-build -W -b doctest -d /Users/hynek/Projects/attrs/.tox/docs/tmp/doctrees docs docs/_build/html'
```
</details>

**Comment by hynek** [comment]
fixed in b7919d0ddd0829108d7230a556274323177cd659
