### ISSUE TITLE
Inheriting from Exception breaks deepcopy on Python 2

### ISSUE THREAD

**Issue by rouge8** [python-attrs/attrs#217]
attrs classes that inherit from `Exception` on Python 2 cannot be deep copied:

```pycon
>>> from copy import deepcopy
>>> import attr
>>> @attr.s
... class Foo(Exception):
...     bar = attr.ib()
...
>>> deepcopy(Foo(1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
TypeError: __init__() takes exactly 2 arguments (1 given)
```

Python 2.7.13, attrs 16.3.0, 17.2.0,and 50107f6 .

This is not an issue on Python 3:

```pycon
>>> from copy import deepcopy
>>> import attr
>>> @attr.s
... class Foo(Exception):
...     bar = attr.ib()
...
>>> deepcopy(Foo(1))
Foo(bar=1)
```

**Comment by rouge8** [comment]
Turns out this isn't attrs related, it's just Python 2 😩 :

```pycon
>>> from copy import deepcopy
>>> class Foo(Exception):
...     def __init__(self, bar):
...         self.bar = bar
...
>>> deepcopy(Foo(1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
TypeError: __init__() takes exactly 2 arguments (1 given)
>>>
```

**Comment by hynek** [comment]
May I suggest Python 3.6? ;)

**Comment by rouge8** [comment]
I wish 😭  Migrating monoliths with poor test coverage will not be fun..
