### ISSUE TITLE
deepcopy stopped working with slots=True and __weakref__ after updating to 17.3.0

### ISSUE THREAD

**Issue by ZlatyChlapec** [python-attrs/attrs#311]
```Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import attr
>>> attr.__version__
'17.3.0'
>>> from copy import deepcopy
>>> @attr.s(slots=True)
... class Han(object):
...     __weakref__ = attr.ib(init=False, hash=False, repr=False, cmp=False)
... 
>>> h = Han()
>>> o = deepcopy(h)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 336, in _reconstruct
    y.__setstate__(state)
  File "/usr/local/lib/python2.7/dist-packages/attr/_make.py", line 432, in slots_setstate
    __bound_setattr(name, value)
AttributeError: attribute '__weakref__' of 'Han' objects is not writable
```

**Comment by Tinche** [comment]
Hm. I'll take a look soonish.

**Comment by hynek** [comment]
Any update Tin?

**Comment by Tinche** [comment]
Uhh totally forgot about this. Will take a look tomorrow.

**Comment by Tinche** [comment]
Plot twist, the above code works on OS X, CPython 3.6.1. But I remember looking at this at home on Linux and it didn't work.

**Comment by hynek** [comment]
It doesn’t work for me on macOS High Sierra and 3.6.3.  Could you maybe have forgotten the decorator?  Happened to me too while checking.

I also think I know what’s happening: attrs deletes `__weakref__` because it’s an attribute.

We’ll have to create a blacklist of things that shouldn’t be deleted.

**Comment by Tinche** [comment]
Running Python docker images on OS X, 2.7.14 and 3.6.4 seem to work?

```
root@ec456701d792:~# cat d.py
import attr
from copy import deepcopy


@attr.s(slots=True)
class Han(object):
    __weakref__ = attr.ib(init=False, hash=False, repr=False, cmp=False)


h = Han()

o = deepcopy(h)
```

**Comment by Tinche** [comment]
>>> I also think I know what’s happening: attrs deletes __weakref__ because it’s an attribute.

We don't do that for slot classes, right?

**Comment by hynek** [comment]
```python
Traceback (most recent call last):
  File "t2.py", line 12, in <module>
    o = deepcopy(h)
  File "/Users/hynek/.virtualenvs/attrs/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/hynek/.virtualenvs/attrs/lib/python3.6/copy.py", line 282, in _reconstruct
    y.__setstate__(state)
  File "/Users/hynek/Projects/attrs/src/attr/_make.py", line 460, in slots_setstate
    __bound_setattr(name, value)
AttributeError: attribute '__weakref__' of 'Han' objects is not writable
```

**Comment by hynek** [comment]
> We don't do that for slot classes, right?

Oh yeah right.  So the bug seems to be in set_state – I’ve just had a look and it doesn’t seem to check for init=False? 🤔

**Comment by Tinche** [comment]
I still can't repro this. 3.6.3 you say?

```
ttvrtkovic@NANOZAGDEV019 ~/p/attrs> docker run --rm -ti -v (pwd):/root python:3.6.3 /bin/bash
Unable to find image 'python:3.6.3' locally
3.6.3: Pulling from library/python
f49cf87b52c1: Already exists
7b491c575b06: Already exists
b313b08bab3b: Already exists
51d6678c3f0e: Already exists
09f35bd58db2: Already exists
1bda3d37eead: Pull complete
9f47966d4de2: Pull complete
9fd775bfe531: Pull complete
Digest: sha256:cdef88d8625cf50ca705b7abfe99e8eb33b889652a9389b017eb46a6d2f1aaf3
Status: Downloaded newer image for python:3.6.3
root@83388638cbc3:/# cd root
root@83388638cbc3:~# pip install -e .
Obtaining file:///root
Installing collected packages: attrs
  Running setup.py develop for attrs
Successfully installed attrs
root@83388638cbc3:~# python -V
Python 3.6.3
root@83388638cbc3:~# cat d.py
import attr
from copy import deepcopy


@attr.s(slots=True)
class Han(object):
    __weakref__ = attr.ib(init=False, hash=False, repr=False, cmp=False)


h = Han()

o = deepcopy(h)
root@83388638cbc3:~# python d.py
root@83388638cbc3:~#
```
Something fishy going on.

**Comment by Tinche** [comment]
I'm an idiot, I wasn't actually on master.

**Comment by Tinche** [comment]
Yeah, I can repro now. I think our `__setstate__` implementation is interacting badly with, well, Python. Consider this:

```
class D:
    __slots__ = ()

>>> d = D()
>>> d.__weakref__ = None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'D' object has no attribute '__weakref__'
```
Why isn't weakref writable? No idea, but it just isn't. So I guess we can't treat it like a normal attribute.

**Comment by Tinche** [comment]
(replaced the last comment with this one)

Yeah, I can repro now. I think our `__setstate__` implementation is interacting badly with, well, Python. Consider this:

```
class D:
    __slots__ = ('__weakref__')

>>> d = D()
>>> d.__weakref__ = None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: attribute '__weakref__' of 'D' objects is not writable
```
Why isn't weakref writable? No idea, but it just isn't. So I guess we can't treat it like a normal attribute.

**Comment by hynek** [comment]
The question now is whether we add some duct tape or add proper weakref support that has been asked for by many people.

As you may suspect, I’m for the latter. :)

**Comment by Tinche** [comment]
Yeah, that'd be for the best probably. Ideas for the API?

**Comment by hynek** [comment]
Paging @njsmith who asked for this feature before. :)

(I think I’ll also additionally add duct tape, that seems to be trivial to fix)
