### ISSUE TITLE
make_class fails if boolean values are present in input dictionary

### ISSUE THREAD

**Issue by gvoysey** [python-attrs/attrs#376]
`foo = attr.make_class(name="Input", attrs={'foo':True})`
```
Traceback (most recent call last):
  File "/Users/gvoysey/.local/share/virtualenvs/corti-LCk1LbZy/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-40c04d4454db>", line 1, in <module>
    attr.make_class(name="Input", attrs={'foo':True})
  File "/Users/gvoysey/.local/share/virtualenvs/corti-LCk1LbZy/lib/python3.6/site-packages/attr/_make.py", line 1474, in make_class
    return _attrs(these=cls_dict, **attributes_arguments)(type_)
  File "/Users/gvoysey/.local/share/virtualenvs/corti-LCk1LbZy/lib/python3.6/site-packages/attr/_make.py", line 671, in wrap
    builder = _ClassBuilder(cls, these, slots, frozen, auto_attribs)
  File "/Users/gvoysey/.local/share/virtualenvs/corti-LCk1LbZy/lib/python3.6/site-packages/attr/_make.py", line 371, in __init__
    attrs, super_attrs = _transform_attrs(cls, these, auto_attribs)
  File "/Users/gvoysey/.local/share/virtualenvs/corti-LCk1LbZy/lib/python3.6/site-packages/attr/_make.py", line 251, in _transform_attrs
    ), key=lambda e: e[1].counter)
  File "/Users/gvoysey/.local/share/virtualenvs/corti-LCk1LbZy/lib/python3.6/site-packages/attr/_make.py", line 251, in <lambda>
    ), key=lambda e: e[1].counter)
AttributeError: 'bool' object has no attribute 'counter'
```
*Versions*
`attrs` 17.4.0
`python` 3.6.3

**Comment by hynek** [comment]
What exactly are you trying to achieve and what gave you the idea, you could pass a Boolean here? The `attrs` argument can be either:

1. a list of strings or
2. a dict of string to Attribute

http://www.attrs.org/en/stable/api.html#attr.make_class

**Comment by gvoysey** [comment]
My mistake.  User error -- I wrote something like this MWE to use attrs with an argparser and emit a class of command line arguments from a dict.  

I believe that when I wrote it, I was only ever passing `--option <value>` style things, so that this ever worked is probably a fluke.
