### ISSUE TITLE
attributes() got an unexpected keyword argument 'frozen'

### ISSUE THREAD

**Issue by iamhmx** [python-attrs/attrs#401]
when i import aiohttp, report a error, blew:
```
import aiohttp
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2869, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-6b0f4dd1af9d>", line 1, in <module>
    import aiohttp
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 19, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 19, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/aiohttp/client.py", line 17, in <module>
    from . import client_exceptions, client_reqrep
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 19, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 17, in <module>
    from . import hdrs, helpers, http, multipart, payload
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 19, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/aiohttp/helpers.py", line 162, in <module>
    @attr.s(frozen=True, slots=True)
TypeError: attributes() got an unexpected keyword argument 'frozen'
```

**Comment by hynek** [comment]
Looks like your version of `attrs` is *very* old. The `frozen` keyword was added in 16.1.0.

**Comment by iamhmx** [comment]
Thanks! Work well after updating!

**Comment by mugbya** [comment]
Thanks, Me too
