### ISSUE TITLE
validation triggered too late

### ISSUE THREAD

**Issue by IaroslavR** [python-attrs/attrs#461]
attrs `18.2.0`
python `3.6.7`
I'm not sure, is it bug or expected behavior, but steps to reproduce:
```python
import attr


def validate_x(_, __, value):
    if value not in ["a", "b", ]:
        raise ValueError(f"Unknown type: {value}")


@attr.s(auto_attribs=True)
class A:
    name: str = attr.ib(validator=validate_x)
    map: dict = {
        "x": 1,
        "y": 2,
    }
    detector: str = attr.ib()

    @detector.default
    def init_detector(self):
        return self.map[self.name]


a = A('c')
```
Expected(by me):
```
Traceback (most recent call last):
  File "/home/mirror/tst.py", line 23, in <module>
    a = A('c')
  File "<attrs generated init 090efc2f40404e910a622fb3a7382642c4cc7dba>", line 9, in __init__
  File "/home/mirror/tst.py", line 6, in validate_x
    raise ValueError(f"Unknown type: {value}")
ValueError: Unknown type: c
```
Real:
```
Traceback (most recent call last):
  File "/home/mirror/tst.py", line 23, in <module>
    a = A('c')
  File "<attrs generated init b58e3f79027d88b47fd9d82dccbb4d2f365e3754>", line 7, in __init__
  File "/home/mirror/tst.py", line 20, in init_detector
    return self.map[self.name]
KeyError: 'c'
```

**Comment by vlcinsky** [comment]
This is expected behaviour.

As stated at http://www.attrs.org/en/stable/init.html?highlight=order#callables

> Since the validators runs after the instance is initialized, you can refer to other attributes while validating:

As defaults are evaluated during initialization, the `init_detector` runs before the validation can take effect.

**Comment by hynek** [comment]
Yes this is indeed on purpose and simply a trade off call we had to make. I believe the way we chose to operate is overall more flexible.

**Comment by vlcinsky** [comment]
Documentation would benefit from one clear statement about order of particular function execution. Currently one has to hunt it in multiple places.

Here is my proposal with demonstration about how it really works:

```python
"""Order of applying attribute default, converter and validator

For each attribute one by one: apply default, then converter.

For each attribute: apply validator

For the instance, call `__attrs_post_init__`

"""
from functools import partial

import attr
from structlog import get_logger

log = get_logger()


def str2int(attname, text):
    log.info("converter", attname=attname)
    return text


def def_factory(attname):
    log.info("def_factory", attname=attname)
    return 123


def is_positive(attname, instance, attribute, value):
    log.info("validator", attname=attname)
    if value <= 0:
        raise ValueError("Value is not positive")


@attr.s
class A:
    a: int = attr.ib(
        default=attr.Factory(partial(def_factory, "a")),
        converter=partial(str2int, "a"),
        validator=partial(is_positive, "a"),
    )
    b: int = attr.ib(
        default=attr.Factory(partial(def_factory, "b")),
        converter=partial(str2int, "b"),
        validator=partial(is_positive, "b"),
    )
    da: int = attr.ib(converter=partial(str2int, "da"))
    db: int = attr.ib(converter=partial(str2int, "db"))

    def __attrs_post_init__(self):
        log.info("within __attrs_post_init__")

    @da.default
    def _da_default(self):
        log.info("default", attname="da")
        return 24

    @da.validator
    def _da_validator(self, attribute, value):
        log.info("validator", attname="da")
        if value <= 0:
            raise ValueError("Value is not positive")

    @db.default
    def _db_default(self):
        log.info("default", attname="db")
        return 24

    @db.validator
    def _db_validator(self, attribute, value):
        log.info("validator", attname="db")
        if value <= 0:
            raise ValueError("Value is not positive")


def test_it():
    inst = A()
    print("inst", inst)
```
Running it (as a pytest driven test case) results in following output:

```
2018-11-06 15:28.33 def_factory                    attname=a
2018-11-06 15:28.33 converter                      attname=a
2018-11-06 15:28.33 def_factory                    attname=b
2018-11-06 15:28.33 converter                      attname=b
2018-11-06 15:28.33 default                        attname=da
2018-11-06 15:28.33 converter                      attname=da
2018-11-06 15:28.33 default                        attname=db
2018-11-06 15:28.33 converter                      attname=db
2018-11-06 15:28.33 validator                      attname=a
2018-11-06 15:28.33 validator                      attname=b
2018-11-06 15:28.33 validator                      attname=da
2018-11-06 15:28.33 validator                      attname=db
2018-11-06 15:28.33 within __attrs_post_init__
inst A(a=123, b=123, da=24, db=24)
```

**Comment by IaroslavR** [comment]
@vlcinsky Tnx. Cristal clear explanation
