### ISSUE TITLE
python3.10 interacts badly with typing_extensions.ClassVar

### ISSUE THREAD

**Issue by graingert** [python-attrs/attrs#781]
```python
from typing import Callable, Optional, ClassVar

import typing_extensions
import attr


@attr.s(auto_attribs=True)
class Ham:
    ham: typing_extensions.ClassVar[int] = 0
    spam: int
    eggs: Optional[int] = attr.ib(init=False, default=None)
```

```pytb
python3.10 foo.py
Traceback (most recent call last):
  File "/home/graingert/projects/twisted/foo.py", line 8, in <module>
    class Ham:
  File "/home/graingert/projects/twisted/.tox/py310-alldeps-nocov/lib/python3.10/site-packages/attr/_make.py", line 1292, in wrap
    builder = _ClassBuilder(
  File "/home/graingert/projects/twisted/.tox/py310-alldeps-nocov/lib/python3.10/site-packages/attr/_make.py", line 604, in __init__
    attrs, base_attrs, base_map = _transform_attrs(
  File "/home/graingert/projects/twisted/.tox/py310-alldeps-nocov/lib/python3.10/site-packages/attr/_make.py", line 518, in _transform_attrs
    raise ValueError(
ValueError: No mandatory attributes allowed after an attribute with a default value or factory.  Attribute in question: Attribute(name='spam', default=NOTHING, validator=None, repr=True, eq=True, order=True, hash=None, init=True, metadata=mappingproxy({}), type='int', converter=None, kw_only=False, inherited=False, on_setattr=None)
```

**Comment by graingert** [comment]
it seems to work fine if I use `from typing_extensions import ClassVar`

```python
from typing import Callable, Optional, ClassVar

from typing_extensions import ClassVar
import attr


@attr.s(auto_attribs=True)
class Ham:
    ham: ClassVar[int] = 0
    spam: int
    eggs: Optional[int] = attr.ib(init=False, default=None)
```

**Comment by euresti** [comment]
Yeah we just do a string comparison on `typing.ClassVar` or `ClassVar`.  Any reason you can't use `from typing import ClassVar`?  (I don't recall which supported versions of python include it these days)

**Comment by graingert** [comment]
@euresti here's the context: 
https://github.com/twisted/twisted/pull/1559/files#diff-592f0a2a781d4b88035bcd58b8686ce792e80e17b7e93cb25bba26efab963250R958

**Comment by graingert** [comment]
I'm avoiding the `from ... import` to avoid clashing with `twisted.internet.Protocol`

**Comment by euresti** [comment]
Ah.  Try 
```
import typing

typing.ClassVar[...]
```

This should be available in python > 3.5.3.

If you need to support older pythons you can put it in quotes. i.e.
```
_log: "typing.ClassVar[Logger]" = Logger()
```

**Comment by euresti** [comment]
Note: `attrs` should probably support `typing_extensions.ClassVar`  I'm just trying to give you a workaround.

**Comment by graingert** [comment]
Ah I should totally be using `from typing import ClassVar` I mistakenly thought it was new in 3.8
