### ISSUE TITLE
`field_transformer` functionality dependent on order of attributes

### ISSUE THREAD

**Issue by jakubpernis** [python-attrs/attrs#812]
Hi, I am using `attrs` (version 21.2.0 and python version 3.8.8) to validate data that come to our prediction endpoint and I noticed possible bug. Here is a simple example for reproducing it.

Let's have two classes defined with function used for automatic converting of values to desired data types:

```
import attr

def auto_convert(cls, fields):
    """Function used for automatic converting of field to wanted data types
       (specified by type hinting in classes decorated with `attr.s`)."""
    results = []


    for field in fields:
        if field.converter is not None:
            results.append(field)
            continue
        elif field.type in [int, float, bool, str]:
            converter = field.type
        elif field.type == Inside:
            converter = lambda x: field.type(**x)
        else:
            converter = None

        results.append(field.evolve(converter=converter))

    return results


@attr.s(auto_attribs=True, kw_only=True, field_transformer=auto_convert)
class Inside:
    a: int
    b: float


@attr.s(auto_attribs=True, kw_only=True, field_transformer=auto_convert)
class Outside:
    x: int
    y: float
    z: float
    inside: Inside
```

now when I do 
```
outside_dict = {
    'x': '10',
    'y': 20,
    'z': 10,
    'inside': {'a': True, 'b': '200'},
}
Outside(**outside_dict)
```
I get
```
Outside(x=10, y=20.0, z=10.0, inside=Inside(a=1, b=200.0))
```

However if I change order of the attributes in `Outside` class, specifically put `z` after `inside`
```
@attr.s(auto_attribs=True, kw_only=True, field_transformer=auto_convert)
class Outside:
    x: int
    y: float
    inside: Inside
    z: float
```

and do the same
```
outside_dict = {
    'x': '10',
    'y': 20,
    'z': 10,
    'inside': {'a': True, 'b': '200'},
}
Outside(**outside_dict)
```
I get an error
```
Traceback (most recent call last):
  File "attr_bug.py", line 49, in <module>
    Outside(**outside_dict)
  File "<attrs generated init __main__.Outside>", line 4, in __init__
  File "attr_bug.py", line 16, in <lambda>
    converter = lambda x: field.type(**x)
TypeError: float() takes no keyword arguments
```

Let me know if you need me to specify anything else.

**Comment by sscherfke** [comment]
This is not an attrs issue but a problem with your `auto_convert` function.

In the line `            converter = lambda x: field.type(**x)` `field` will always be the value of the *last field of the iteration* and **not** the value of the current iteration.

Below you'll find a working version of your example. The project [typed-settings](https://typed-settings.readthedocs.io/en/latest/index.html) also [defines a well tested auto-convert hook](https://typed-settings.readthedocs.io/en/latest/apiref.html#typed_settings.attrs.hooks.auto_convert) which may eventually be integrated into attrs.

```python
import attr

def auto_convert(cls, fields):
    """Function used for automatic converting of field to wanted data types
       (specified by type hinting in classes decorated with `attr.s`)."""
    results = []


    for field in fields:
        if field.converter is not None:
            results.append(field)
            continue
        elif field.type in [int, float, bool, str]:
            converter = field.type
        elif field.type == Inside:
            converter = mk_attrs_converter(field.type)
        else:
            converter = None

        results.append(field.evolve(converter=converter))

    return results


def mk_attrs_converter(type):
    def convert(val):
        return val if isinstance(val, type) else type(**val)
    return convert


@attr.s(auto_attribs=True, kw_only=True, field_transformer=auto_convert)
class Inside:
    a: int
    b: float


@attr.s(auto_attribs=True, kw_only=True, field_transformer=auto_convert)
class Outside:
    x: int
    y: float
    inside: Inside
    z: float


outside_dict = {
    'x': '10',
    'y': 20,
    'z': 10,
    'inside': {'a': True, 'b': '200'},
}
print(Outside(**outside_dict))
```

**Comment by jakubpernis** [comment]
Oh I see. Thanks for the prompt answer and the solution 👍
