### ISSUE TITLE
Using unittest.mock on attributes of frozen attr object raises FrozenInstanceError

### ISSUE THREAD

**Issue by jessebrennan** [python-attrs/attrs#838]
This applies to all kinds of attributes, but for me specifically it's a class attribute. Here's what I was trying to do:

```
from unittest.mock import patch
import attr


@attr.s(frozen=True)
class Foo:
    bar: ClassVar[int] = 9
    
f = Foo()
with patch.object(f, 'bar', 10):
    print(f.bar)
    
Traceback (most recent call last):
  File "/home/jesse/.pyenv/versions/3.8.3/lib/python3.8/unittest/mock.py", line 1490, in __enter__
    setattr(self.target, self.attribute, new_attr)
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/attr/_make.py", line 419, in _frozen_setattrs
    raise FrozenInstanceError()
attr.exceptions.FrozenInstanceError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-32-d06153be6581>", line 1, in <module>
    with patch.object(f, 'bar', 10):
  File "/home/jesse/.pyenv/versions/3.8.3/lib/python3.8/unittest/mock.py", line 1503, in __enter__
    if not self.__exit__(*sys.exc_info()):
  File "/home/jesse/.pyenv/versions/3.8.3/lib/python3.8/unittest/mock.py", line 1511, in __exit__
    delattr(self.target, self.attribute)
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/attr/_make.py", line 426, in _frozen_delattrs
    raise FrozenInstanceError()
attr.exceptions.FrozenInstanceError
```

Probably there's nothing to be done here.. it makes sense why this would fail. I could unfreeze the object, but that's less than ideal. Making a copy doesn't work because the class attribute isn't a parameter. Any ideas or suggestions would be helpful.

**Comment by jessebrennan** [comment]
I'm going to close this as a non-issue since I realized I can just mock the class instead of the instance a la:

```
from unittest.mock import patch
import attr


@attr.s(frozen=True)
class Foo:
    bar: ClassVar[int] = 9
    
f = Foo()
with patch.object(f, 'bar', 10):
    print(f.bar)
```
