### ISSUE TITLE
Why descriptor don't work with attr?

### ISSUE THREAD

**Issue by jalvespinto** [python-attrs/attrs#881]
I am reading Architecture Patterns with Python and at some point the frozen dataclasses just don't work with sqlalchemy, so the author suggests setting `unsafe_hash=True`. To avoid making the class hashable I am using the descriptor bellow. I was also using `@attr.s` instead of `@dataclass` to get some of the features it has, like validators, but for some reason the descriptor works fine with dataclass, but not with attr and I can't understand why and if there is a way to make it work. If I set `init=False` on the attr.s class the descriptor will work for `self.vid` the I am only setting inside the __init__, but don't work with `street` and `number`. 
```
from dataclasses import dataclass
import attr
import uuid


class Frozen:
    """cannot change attribute if it already exists"""

    def __set_name__(self, owner, name):
        self.storage_name = '_' + name

    def __set__(self, instance, value):
        if hasattr(instance, self.storage_name):
            raise AttributeError(
                f'readonly attribute {value.__class__.__name__}')
        else:
            setattr(instance, self.storage_name, value)

    def __get__(self, instance, objtype=None):
        return getattr(instance, self.storage_name)

# Frozen descriptor works fine here
@dataclass
class Address:

    vid = Frozen()
    street = Frozen()
    number = Frozen()

    street: str
    number: str

    def __init__(self, street: str, number: str, vid=None) -> None:
        self.street = street
        self.number = number
        self.vid = vid if vid else uuid.uuid4().hex

# Frozen descriptor don't work here
@attr.s
class Address:

    vid = Frozen()
    street = Frozen()
    number = Frozen()

    street: str = attr.ib
    number: str = attr.ib

    def __init__(self, street: str, number: str, vid=None) -> None:
        self.street = street
        self.number = number
        self.vid = vid if vid else uuid.uuid4().hex
```

**Comment by hynek** [comment]
Try setting `@attr.s(auto_attribs=True)` (or even better: use `@attr.define`) and dropping the `= attr.ib`. You're overwriting both street and number this way.

Note that you can just use `@attr.s(frozen=True)` or `@attr.frozen` to get a frozen class.

**Comment by hynek** [comment]
Ah you're using additional attributes. Try `@attr.define(slots=False)` then.

**Comment by jalvespinto** [comment]
But even without them, the descriptors won't work. The behavior I am seeing is that any field I declare will override the descriptor, so the descriptor will not work. If I don't declare the fields and just set them on __init__ the descriptor will work, but I don't see the attribute when invoking the instance:
 ```
@attr.define(slots=False)
class Address:

    vid = FrozenLeadingUnder()
    street = Frozen()
    number = Frozen()

    def __init__(self, street: str, number: str, vid=None) -> None:
        self.street = street
        self.number = number
        self.vid = vid if vid else uuid.uuid4().hex

>>> a = Address('bla','ble')
>>> a.street = 'dfad'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/usr/test.py", line 35, in __set__
    raise AttributeError(
AttributeError: readonly attribute str
>>> a
Address()
```

**Comment by hynek** [comment]
You have to annotate street and number if attrs is to find them.

**Comment by jalvespinto** [comment]
yes, but in that case the descriptor will not work:
```
>>> a = b.Address('ba','be')
>>> a.street = 'fadfadf'
>>> a
Address(street='fadfadf', number='be')
>>> 
```

**Comment by hynek** [comment]
I have tried:

```python
@attr.define(slots=False)
class Address:

    street: str = Frozen()
    number: str = Frozen()
    vid: str = Frozen()
```

And I get:

```python
In [2]: a = Address("x", "y", "z")

In [3]: a
Out[3]: Address(street='x', number='y', vid='z')

In [4]: a.street = "asdf"
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-f728b241b7ae> in <module>
----> 1 a.street = "asdf"

~/FOSS/attrs/t.py in __set__(self, instance, value)
     12     def __set__(self, instance, value):
     13         if hasattr(instance, self.storage_name):
---> 14             raise AttributeError(
     15                 f'readonly attribute {value.__class__.__name__}')
     16         else:

AttributeError: readonly attribute str
```

The attribute name is wrong, but it seems to work otherwise?

**Comment by euresti** [comment]
So I'm wondering if this is a typo?

```
# Frozen descriptor don't work here
@attr.s
class Address:
    <snip>
    street: str = attr.ib
```

That should in theory be `attr.ib()`. otherwise attr.s is doing nothing with that and it's just overwriting the Frozen that's going on above.

**Comment by jalvespinto** [comment]
oh, I see. I was doing two different assignments to the same name, one for the descriptor and another for the actual attributes, just like the way I was doing with dataclass. I wonder why that works with dataclass and not with attrs. It seems `slots=False` will do it. I will refactor everything and then come here to let you know how it went, for good or bad. tks

**Comment by euresti** [comment]
Note that this:
```
@attr.define(slots=False)
class Address:
    street: str = Frozen()
    number: str = Frozen()
    vid: str = Frozen()
```

has a problem where attrs thinks that `Frozen()` is a default value.
So it lets you do this:
```
>>> Address()
Address(street=<foo.Frozen object at 0x7fab78034df0>, number=<foo.Frozen object at 0x7fab78034ca0>, vid=<foo.Frozen object at 0x7fab78034e20>)
>>> 
```

So you'll probably want to write your own `__init__`
```
@attr.define(slots=False)
class Address:
    street: str = Frozen()
    number: str = Frozen()
    vid: str = Frozen()

    def __init__(self, street: str, number: str, vid=None) -> None:
        self.street = street
        self.number = number
        self.vid = vid if vid else uuid.uuid4().hex
```

**Comment by jalvespinto** [comment]
noted. tks

**Comment by hynek** [comment]
As a random though: I think you could use field hooks to remove Frozen as the default value: https://www.attrs.org/en/stable/extending.html#automatic-field-transformation-and-modification

maybe they could be useful to you in general.
